### ISSUE TITLE
Encouraging newbies to use Python 2.7.10 or better still Python 3.x

### ISSUE THREAD

**Issue by mickeypash** [leifos/tango_with_django_19#1]
Hey guys,

You might have already considered this but the book currently encourages uses to install Python `2.7.5` which was release in May 2013. 
- The [release notes for Django 1.9](https://docs.djangoproject.com/en/1.9/releases/1.9/#python-compatibility) say that they

> **highly recommend** and only officially support the latest release of each series.
- Here is Guido (BDFL) telling folks to use [Python 3 at PyCon 2015](https://www.youtube.com/watch?v=G-uKNd5TSBw).
- An older version of his slides [can be found here](https://www.dropbox.com/s/83ppa5iykqmr14z/Py2v3Hackers2013.pptx)

Regards

**Comment by maxwelld90** [comment]
Mickey,

We’re going to use Python 3.4/3.5 and 2.7.11. 2.7.5 is old, yes; we’re working through the book to update it.

David
