### ISSUE TITLE
Chapter 6 text in section just before "Migration Woes"

### ISSUE THREAD

**Issue by martindegroot** [leifos/tango_with_django_19#11]
Citation of relevant text on page 56:

> We could **of added** the unique constraint earlier, but if we performed the migration and set 
> everythingto be an empty string by default it would have **given raised an error**. This is because the unique constraint would have been violated. We could **of deleted** the database and then recreated everything - but that is not always desirable

Suggestions:  We could have added

**Comment by martindegroot** [comment]
I accidentally committed my new issue before I was finished. So here is the rest:

Second suggestion:  ... it would have given an error...  or ...it would have raised an error...
Third suggestion: We could have deleted the database...

Martin de Groot

**Comment by leifos** [comment]
Thanks - and now I realize that my Australian English is not Oxford :-)
