### ISSUE TITLE
Chapter 6.3 - PageAdmin not registered anymore in rango/admin.py 

### ISSUE THREAD

**Issue by matonsjojc** [leifos/tango_with_django_19#14]
Page 63, where we customize the admin interface to pre-populate the slug field automatically:

admin.site.register(Page)

We registered PageAdmin in the 5th chapter already (exercise), so I think this line should be replaced with admin.site.register(Page, PageAdmin) or absent from that excerpt completely (since we are dealing only with CategoryAdmin here).

**Comment by leifos** [comment]
Good Call!
