### ISSUE TITLE
Chapter 7 add+page view errors

### ISSUE THREAD

**Issue by martindegroot** [leifos/tango_with_django_19#19]
Page 71 in my epub version, within rango/views.py  def add_page:

if cat:   should become if category:  because cat is not a variable, but category is.

In the line return category(request, category_name_slug)  

should be corrected to:

return show_category(request, category_name_slug)

because there is no view function category, but there is the view function show_category

Martin de Groot

**Comment by leifos** [comment]
Thanks - well spotted. In upgrading from 1.7, I started to change the names of variables so that they were more readable, but missed out a few references! sorted now!
