### ISSUE TITLE
Typo in section "Tests" of chapter 5

### ISSUE THREAD

**Issue by martindegroot** [leifos/tango_with_django_19#2]
Hello authors,

I am not sure if this is the place to mention typo's or things which are not clear, so let me know if I should use another method to communicate with you.

The last but one paragraph in section "Tests" of chapter 5 says to use the following command:
python manage. py tests rango
But when I do this I get an error about tests not being known or found.
Then I checked the official Django tutorial (with the polls app)  and  found the command needs to be:

python manage.py test rango

It only differs from not having the s after test, but it makes all the difference.

Please let me know if you are interested in hearing more remarks like the above, if I find other places in the chapters of your book where something doesn't look quite right to me.

Greetings,
Martin de Groot
Newbie to Python and Django

**Comment by maxwelld90** [comment]
Hi Martin,
Thanks for spotting this typo - it has just been fixed! Appreciate your help!

Cheers,
David

PS This is the perfect place to raise issues like this - no matter how trivial you may feel they are, we'd love to hear them! :)

**Comment by leifos** [comment]
Hi Martin, 

And thanks for all the other suggestions comments too. We have some deadlines and exams to mark - but once that is done we'll be going through the rest...

Cheers
Leif
