### ISSUE TITLE
Chapter 7 Unclear - patterns import not explained

### ISSUE THREAD

**Issue by cspollar** [leifos/tango_with_django_19#22]
I could not find an explanation of why "patterns" is included in rango/urls.py. Previous and later examples of this file do not include "patterns".

The text in question is copied below.

Parameterised URL Mapping
Now let’s have a look at how we actually pass the value of the category_name_url parameter to the category() function. To do so, we need to modify Rango’s urls.py file and update the urlpatterns tuple as follows.

urlpatterns = **patterns('',**
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about, name='about'),
        url(r'^category/(?P<category_name_slug>[\w-]+)/$',
        views.show_category, name='show_category'),)

**Comment by leifos** [comment]
Hi! Well spotted. it is not needed. it should be:

urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'about/$', views.about, name='about'),
url(r'^add_category/$', views.add_category, name='add_category'),
url(r'^category/(?P<category_name_slug>[\w-]+)/$',
views.show_category, name='show_category'),
]

I will update it shortly.

Thanks
Leif

**Comment by leifos** [comment]
Thanks
