### ISSUE TITLE
Typo in Chapter 11 Section 5

### ISSUE THREAD

**Issue by McMutton** [leifos/tango_with_django_19#25]
[In this section](http://www.tangowithdjango.com/book17/chapters/cookie.html#client-side-cookies-a-site-counter-example), we have the lines below for the **index** view: 

```
    # Get the number of visits to the site.
    # We use the COOKIES.get() function to obtain the visits cookie.
    # If the cookie exists, the value returned is casted to an integer.
    # If the cookie doesn't exist, we default to zero and cast that.
    visits = int(request.COOKIES.get('visits', '1'))
```

The comment says that we default the value to **zero** actually it is defaulted to **one**

**Comment by leifos** [comment]
Thanks!

**Comment by maxwelld90** [comment]
Magic!
