### ISSUE TITLE
CH 6 possible edits.

### ISSUE THREAD

**Issue by xmc2** [leifos/tango_with_django_19#27]
At the end of chapter 6 (currently page 69) in the index.html update I believe 

and `{% load staticfiles %}`
should be part of the header.

**Comment by leifos** [comment]
Thanks Matt,

Next week, I will be actively work on TwD so I will fix it then. But, yes,
you'll definitely need load staticfiles, but category or category.name
should be fine. if you use just use category then the "**str**" method will
be called which returns the name :-)

I hope that helps
Leif

**Comment by maxwelld90** [comment]
Yup, can confirm {% load staticfiles %} is now in the index.html template modifications. I'll close this - let us know if you spot anything else. Thank you!
