### ISSUE TITLE
Ch 8 exercise issue

### ISSUE THREAD

**Issue by Amertz08** [leifos/tango_with_django_19#28]
The 3rd exercise asks you to update `restricted.html` to use the base template. Don't believe we get to creating that file till later. Awesome book btw.

**Comment by leifos** [comment]
Hi Adam,

Thanks, glad you're enjoying the book - we re-jigged a few things around from the last version. I'll add that to the todo list to sort out (hopefully this weekend). 

let us know if you spot anything else, and how you get on.

Cheers
Leif

**Comment by maxwelld90** [comment]
Hi Adam,
Thanks for this - excellent spot. The issue still remains. I moved the exercise to Chapter 9. in Chapter 9, you create the restricted view - as you quite rightly pointed out. So by moving the exercise to the end of Ch9, everything is now consistent. I'll close this now - but thanks for the spot!

**Comment by maxwelld90** [comment]
PS I added you to the acknowledgements page - thanks for your efforts!
