### ISSUE TITLE
Chapter 4 - Templates and Static Media - different strings

### ISSUE THREAD

**Issue by matonsjojc** [leifos/tango_with_django_19#3]
page 30: you use the string "Crunchy, creamy, cookie, candy, cupcake!" in context_dict but then you refer to it as "I am bold font from the context" when explaining what the template context is and in a screenshot a bit lower. 

I really love your book so far and am looking forward to doing some nice things with Django.

Regards, M.

**Comment by maxwelld90** [comment]
Hey!
Yes, I don't know when this was changed!!!! But I have updated the screenshot now to reflect the different text, thank you for spotting this. Much appreciated :)

The change will appear when we publish the next iteration.

Cheers,
David
