### ISSUE TITLE
Ch 10.5 pg 124

### ISSUE THREAD

**Issue by Amertz08** [leifos/tango_with_django_19#30]
I think there might be a small error on that page. This is how it is written but that will throw an `UnboundLocalError` since `visits` is reference before assignment. It does look like it is corrected on pg 127 though.

``` python
def visitor_cookie_handler(request):
    visits_cookie = int(request.COOKIES.get('visits', 1))

    last_visit_coookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_coookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits_cookie + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_coookie
    request.session['visits'] = visits
```

**Comment by Amertz08** [comment]
Can send PR on this.

**Comment by rayiyaoyao** [comment]
It seems that the default value of visits doesn't work. 
Add _visits = 1_ after _else:_ just like this:

```


    if(datetime.now() - last_visit_time).days > 0 :
        visits = visits_cookie + 1
        response.set_cookie('last_visit', str(datetime.now()))
    else:
        visits = 1
        response.set_cookie('last_visit', last_visit_cookie)

```

It worked!
Though, I really don't know how this happened. I am a learner, too.

**Comment by maxwelld90** [comment]
Good spot, Adam, many thanks. The first version is indeed incorrect. `visits` should be `visits_cookie` - but I renamed them in the first snippet to match the second snippet (i.e. `visit`).

@rayiyaoyao - Yeah - `visits` wouldn't be declared otherwise, hence the error.

Many thanks for the spot! Cheers!
