### ISSUE TITLE
Ch 11.3 MyRegistration view issue

### ISSUE THREAD

**Issue by Amertz08** [leifos/tango_with_django_19#31]
The code provided for modifying the registration view appears to be incorrect. The first block is what is in the book.

``` python
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/'
```

But if you follow the class inheritance down to `RegistrationView` in `registration/views.py` the `get_success_url` signature is the following.

``` python
def get_success_url(self, user=None):
    """
    Use the new user when constructing success_url.

    """
    return super(RegistrationView, self).get_success_url()
```

And thus I believe this is the correct definition and doesn't cause any errors to be thrown.

``` python
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'
```

**Comment by maxwelld90** [comment]
Spot on - thanks for reporting this. I think were still using an older version of django-registration-redux there. Corrected and updated. Many thanks.
