### ISSUE TITLE
9.6 Creating register() View

### ISSUE THREAD

**Issue by aisflat439** [leifos/tango_with_django_19#33]
I get a syntax error here every time. I'm using python3 and the correct django but there may be some setting. It's fixed by adding parens on the print statement.
`else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print user_form.errors, profile_form.errors
    else:
        # Not a HTTP POST, so we render our form using two ModelForm`

**Comment by maxwelld90** [comment]
Hi - thanks for this. What chapter/section was this in? We've just gone through the latter chapters over the past few days and picked up a load of issues like this. I'll leave this open for now...

Cheers,
David

**Comment by maxwelld90** [comment]
I just saw it, I've patched it up. I'll close this now.
