### ISSUE TITLE
9.7 creating the login() view

### ISSUE THREAD

**Issue by aisflat439** [leifos/tango_with_django_19#34]
print statement for login details had syntax error. Again I'm not sure that this isn't my enviroment specific.

doing it the way I did below solves that issue
`print("Invalid login details: {0}, {1}".format(username, password))`

**Comment by maxwelld90** [comment]
Thanks for the spot! Yes, this should have parenthesis wrapped around like you have. In Python 2, print is a distinct keyword; in Python 3, it's just a regular function. Python 2 also supports the regular print() function, so it makes sense to wrap everything up in parentheses.

I'm going to add you to the acknowledgements page to thank you for your efforts! If you spot anything else, please let us know. Cheers!
