### ISSUE TITLE
(Possible edit needed) 11. User Authentication with Django-Registration-Redux

### ISSUE THREAD

**Issue by aisflat439** [leifos/tango_with_django_19#35]
"However, such functionality is common to many web application so developers have **crated** numerous add-on" I think you mean **created**

**Comment by leifos** [comment]
Yes, created, but crated.. is actually pretty funny.

Thanks for passing on these edits - I’ll be working on finishing off the book next week!

Leif

On 18 Sep 2016, at 15:48, Devin Fitzsimons <notifications@github.com<mailto:notifications@github.com>> wrote:

"However, such functionality is common to many web application so developers have crated numerous add-on" I think you mean created

**Comment by aisflat439** [comment]
If there is something I can do please let me know. I just went through the book last week. It was very good thanks
