### ISSUE TITLE
Issues on 'A CSS Crash Course Chapter'

### ISSUE THREAD

**Issue by pzkpfwVI** [leifos/tango_with_django_19#39]
There is code instead of browser outputs in multiple examples. Like this one on page 267 on the pdf file:

![screenshot - 10042016 - 11 36 53 am](https://cloud.githubusercontent.com/assets/8700952/19067440/e478e8da-8a26-11e6-8cc7-4ebec4f25bc4.png)

**Comment by maxwelld90** [comment]
Thanks. It seems like the publishing tool didn't like our code samples. I'll need to actually go back and take screenshots of everything.

**Comment by leifos** [comment]
:-( that sucks.

Dr. Leif Azzopardi
Chancellor's Fellow / Senior Lecturer
Dept. of Computer & Information Sciences
University of Strathclyde
Glasgow

Ph: 0141 548 3617
Email: leif.azzopardi@strath.ac.ukmailto:leif.azzopardi@strath.ac.uk
Alt Email: leifos@acm.orgmailto:leifos@acm.org
Skype: leifos
Twitter: leifos
GitHub: leifos

On 4 Oct 2016, at 09:41, David Maxwell <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks. It seems like the publishing tool didn't like our code samples. I'll need to actually go back and take screenshots of everything.

**Comment by maxwelld90** [comment]
I'll just fix them now. When I have added in the screenshots, I'll republish the book, and add pzkpfwVI into the acks. Cheers!

**Comment by maxwelld90** [comment]
Problem solved; images added. Will be publishing an updated version very shortly. Thanks for the spot, @pzkpfwVI - I have added you to the acknowledgements section.

**Comment by pzkpfwVI** [comment]
You're welcome and thanks for such a great book

**Comment by maxwelld90** [comment]
Thanks, glad you're liking it :)
