### ISSUE TITLE
Chapter 5 Exercises reference to official Django Tutorial could be improved

### ISSUE THREAD

**Issue by martindegroot** [leifos/tango_with_django_19#4]
Hello Leif and David,

On page 49, section Exercises of chapter 5 you write:

Undertake the second part of the official Django tutorial if you have not already done so. This will help to reinforce further what you have learnt here, and to learn more about customising the admin interface.
    Customise the admin interface. Change it in such a way so that when you view the Page model, the table displays the category, the name of the page and the url - just like in the screenshot shown below.

The link to the "second part of the official Django tutorial" correctly points to "Writing your first Django app, part 2"  But the place in the Django Tutorial where you can learn more about customising the admin interface is not in part 2, but as the third topic in the last part of the tutorial, which is part 7.  The topic is called "Customize the admin change list".

As it stands now, you are pointing the reader to part 2, but you want him or her to learn about the topic in part 7.  I had already done the whole tutorial before coming to your book, so I was able to find where I had read about showing multiple fields instead of the **str** representation by using list_display.
But a new reader, who starts with your book, would be at a loss about finding this if he starts at part 2.

Maybe referring to part 7 of the official tutorial would be more helpful to the reader than pointing to part 2.

I am enjoying working with your book so far.

Greetings, Martin de Groot

**Comment by maxwelld90** [comment]
Hi Martin,
Thanks for your feedback. You are correct - we emphasise you should go to section 2 to reinforce your knowledge on the admin interface, but section 2 only provides details on getting up to speed with Django and the ORM in general.

What I've done is update the repo with a comment explaining what section 2 provides, and added a further exercise for readers to jump to part 7. I think that addresses the issue; I'll leave this open if you have any feedback. Changes will be applied when we release the next iteration of the book.

Cheers, your comments are greatly appreciated by Leif and myself :)
David
