### ISSUE TITLE
Link pg 4, to "how to tango with django website" is dead

### ISSUE THREAD

**Issue by dariushazimi** [leifos/tango_with_django_19#40]
Hi there.

page 4
section 1.4
Link to "how to tango with django website" is not working.

reading your book.

so far so good. :)
Thank you for all your efforts.

**Comment by leifos** [comment]
Hi Darius,

Thanks for letting me know - I’m not exactly sure what happened, but I’ve restarted the website and it seems to be up and running again.

Do let us know how you get on with the book.

Cheers,
Leif

Dr. Leif Azzopardi
Chancellor's Fellow / Senior Lecturer
Dept. of Computer & Information Sciences
University of Strathclyde
Glasgow

Ph: 0141 548 3617
Email: leif.azzopardi@strath.ac.ukmailto:leif.azzopardi@strath.ac.uk
Alt Email: leifos@acm.orgmailto:leifos@acm.org
Skype: leifos
Twitter: leifos
GitHub: leifos

On 5 Oct 2016, at 20:44, Darius <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi there.

page 4
section 1.4
Link to "how to tango with django website" is not working.

reading your book.

so far so good. :)
Thank you for all your efforts.
