### ISSUE TITLE
base.html instead of index.html on page 122

### ISSUE THREAD

**Issue by ma-152478** [leifos/tango_with_django_19#43]
The PDF says on page 122:"Like in the previous section, we’ll be modifying Rango’s index.html template and ..." but the file "base.html" should be modified, shouldn't it?

**Comment by ma-152478** [comment]
and I think on page 129 it should be "Now navigate to the ABOUT page" instead of registration page, because the cookie-testing was added to the about() view.

**Comment by maxwelld90** [comment]
Ahaha, thank you for the spot. Fixed! Cheers!
