### ISSUE TITLE
/python_books/ doesn't return 404 as mentioned in Chap 6 > Parameterised URL Mapping section

### ISSUE THREAD

**Issue by ProProgrammer** [leifos/tango_with_django_19#47]
Chapter 6 > Parameterized URL mapping section mentions that 

> if the URL was rango/category/python_books/ or rango/category/££££-$$$$$/ then the sequence of characters between rango/category/ and the trailing / would not match the regular expression, and a 404 not found error would result

_(This line is just before info section titled **Regex Hell**)_

This is not true in the case of path `rango/category/python_books/`. Accessing this page returns HTML with test "The specified category does not exist" instead of 404. It looks like the underscores are matched by regex `\w` as per what is mentioned on [Regular-Expressions.info](http://www.regular-expressions.info/shorthand.html)

> \w stands for "word character". It always matches the ASCII characters [A-Za-z0-9_]. Notice the inclusion of the underscore...

**Comment by maxwelld90** [comment]
Hi @ProProgrammer, thanks for this. I'll have a look into this and see what I need to revise. Cheers!

**Comment by maxwelld90** [comment]
Hi @ProProgrammer, thanks for this. I am updating the book, and took out the first example -- which does not yield a 404 as you say. Thank you for the spot!

Cheers,
David
