### ISSUE TITLE
Link broken: Git server tutorial

### ISSUE THREAD

**Issue by reggaedit** [leifos/tango_with_django_19#48]
Hi there,

Excellent book! Just noticed a broken link on the git chapter: A Git Crash Course:
https://github.com/leifos/tango_with_django_19/blob/master/manuscript/chapter-git.md

http://ww38.seifeet.com/2012/11/centos-63-configuring-git-server.html <-- domain is for sale.

**Comment by maxwelld90** [comment]
Thanks for the spot! I'll fix this shortly.

David

**Comment by maxwelld90** [comment]
Checked everything again and link fixed. Thank you!

**Comment by reggaedit** [comment]
No problem
