### ISSUE TITLE
Chapter 5 section Tests displays formatting instruction

### ISSUE THREAD

**Issue by martindegroot** [leifos/tango_with_django_19#5]
Hello Leif and David,

The second paragraph in the last section "Tests" of chapter 5 reads:

To run the tests, issue the following command in the terminal:
    {lang=”text”,linenos=off}
        $ python manage.py tests rango

I think you don't want the text in curly brackets to be printed. It seems to me that they are formatting instructions which probably have an error in them, so that they are not interpreted as formatting instructions but are printed as text.

Martin de Groot

**Comment by maxwelld90** [comment]
Hi Martin,
Thanks for spotting that - I've fixed it in the repo. The fix will appear when the next iteration of the book is published. Thanks for your help!

Cheers
David
