### ISSUE TITLE
Seven tests from test.py referenced on page 69 of the .pdf may need correcting

### ISSUE THREAD

**Issue by mccordgh** [leifos/tango_with_django_19#50]
### These tests should be passing at this point in the tutorial, as the content is there (except for the last mentioned).
___
Line 106 in test_index_contains_hello_message (rango.tests.Chapter4ViewTests) throws:
    TypeError: a bytes-like object is required, not 'str'
___
Line 111 in test_does_index_contain_img (rango.tests.Chapter4ViewTests) throws:
    TypeError: a bytes-like object is required, not 'str'
___
Line 123 in  test_does_about_contain_img (rango.tests.Chapter4ViewTests) throws:
    TypeError: a bytes-like object is required, not 'str'
___
Line 128 in test_about_contains_create_message (rango.tests.Chapter4ViewTests) throws:
    TypeError: a bytes-like object is required, not 'str'
___
Line 178 in test_admin_interface_page_view (rango.tests.Chapter5ViewTests) throws:
    ModuleNotFoundError: No module named 'admin'
___
Line 171 in test_view_has_title (rango.tests.Chapter5ViewTests) throws:
    TypeError: a bytes-like object is required, not 'str'
___
Line 207 in test_does_slug_field_work (rango.tests.Chapter6ViewTests) throws:
    AttributeError: 'Category' object has no attribute 'slug'

It seems that __slug field__ isn't even reference for another 4 pages after we are told to download tests.py and run it with python manange.py test rango

**Comment by 0mician** [comment]
Hi Mat, the changes in this commit/PR should work https://github.com/leifos/tango_with_django_19/pull/51/commits/9671db4c97e56d5c56f626ada7918593f8e3a758

**Comment by mccordgh** [comment]
Those tests worked great on my end, thank you.

**Comment by maxwelld90** [comment]
Hi @mccordgh, can I please ask what version of Python were you running when the tests failed?
