### ISSUE TITLE
get_success_url ( RegistrationView )  does not work 

### ISSUE THREAD

**Issue by vankhoa011** [leifos/tango_with_django_19#58]
Hello,

I just went through the Django 1.9. I want that after registration , there will have redirect to 'user_profile', however, It does not work . Any sugggestion.

from registration.backends.simple.views import RegistrationView

```
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/register_profile'


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rango/', include('rango.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

```

**Comment by vankhoa011** [comment]
Oh, I knew the problem now. Just change the order of url. However, Do you know why ? 
```
    url(r'^accounts/register/$', views.RangoRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
```

**Comment by leifos** [comment]
Yes, the order matters. The django machinery will go through each pattern, one at a time, in order, so if it finds a match, then it will try execute the corresponding view.

This is a good point to note for the next edition!

Thanks
Leif

**Comment by vankhoa011** [comment]
@leifos : thank you for your information.
