### ISSUE TITLE
Chapter 5 - Models and Databases - repeated lines in population script

### ISSUE THREAD

**Issue by matonsjojc** [leifos/tango_with_django_19#6]
Page 50: I think lines from 56-59 in the population script are repeated unnecessarily from 61-64.

**Comment by martindegroot** [comment]
I agree with matonsjojc that lines 61-64 are a duplicate of lines 56-59. In my epub version of the book, after first update, this is on page 46 out of 117 pages.

Martin de Groot

**Comment by leifos** [comment]
Thanks - I just removed the stutter code :-)
