### ISSUE TITLE
Chapter 6 - Models, Templates and Views - {% load staticfiles %} deleted from index.html

### ISSUE THREAD

**Issue by matonsjojc** [leifos/tango_with_django_19#7]
There is no more {% load staticfiles %} line in updated index.html (page 59). I do not understand why - shouldn't this line remain in the file, since we still want to show static files (rango.jpg). I see it works with or without that line - could you put that line back or offer an explanation, why it is not needed?

Also, the screenshot on page 60 shows a category named Python User Groups, which was not added by the population script (edit: I see this category is added manually later...).

Regards, Matevž

**Comment by leifos** [comment]
Thanks.. I've added the line back in, but I am wondering why it would work without the line... I was just reading the docs and it says it is required.. I will try it out.. but in any case, thanks, i've added it back :-)
