### ISSUE TITLE
Chapter 6.2 subsection Modifying the Index view [:5] list slice is first five, not last five

### ISSUE THREAD

**Issue by martindegroot** [leifos/tango_with_django_19#8]
Citation of relevant text in the book:

> Since a list of Category objects will be returned, we used Python’s list operators to take **the last five** >objects from the list i.e  [:5] and thus return a sub-list of Category objects

The slice operators a_list[:5]  is equivalent to alist[0:5] 

This is a sub-list of a_list containing the items with index from 0 upto and including 4, in other words **the first five** items of the original list. 

Martin de Groot

**Comment by leifos** [comment]
Thanks!
