### ISSUE TITLE
Chapter 6 url of the index view is different from the same index view url in chapter 4

### ISSUE THREAD

**Issue by martindegroot** [leifos/tango_with_django_19#9]
In chapter 4 the url of the index view is (page 31 and page 34)

> http://127.0.0.1:8000/rango/

But in chapter 6, after adding the top 5 liked categories to the page, it suddenly changes to:

> http://127.0.0.1:8000/

There is nothing in the book between chapters 4 and 6 where the index view is linked to this last url, so I believe this is a mistake. 

Martin de Groot

**Comment by leifos** [comment]
For consistency I have updated it include the rango/, but in the url mappings, we have a mapping that directs 
http://127.0.0.1:8000/
to the rango application.. but I guess we should probably explain that :-)
